spring.application.name=chatApp

spring.data.mongodb.uri=mongodb://localhost:27017/chatDB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tanmoycoursera@gmail.com
spring.mail.password=sxniswzcmhyvwxzz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true